name: deploy

on:
  push:
    branches:
      - main

jobs:
  caprover:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./loki/
    strategy:
      fail-fast: true
      matrix:
        image: [loki, alloy]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: docker.mattglei.ch
          username: admin
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -t docker.mattglei.ch/lab/${{ matrix.image }} .
          docker push docker.mattglei.ch/lab/${{ matrix.image }}
      - uses: caprover/deploy-from-github@v1.1.2
        with:
          server: https://lab.mattglei.ch
          app: ${{ matrix.image }}
          token: '${{ secrets.CAPROVER_PASSWORD }}'
          image: docker.mattglei.ch/lab/${{ matrix.image }}
